run:
  timeout: 5m
  tests: true
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - errorlint
    - bodyclose
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - usetesting
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - gci

issues:
  exclude-dirs:
    - vendor
    - test
  exclude-rules:
    - path: _test\.go
      linters:
        # The list of linters below is exhaustive with respect to the linters defined above, and as such, and linter
        # that needs to be run on test files should be dropped from here.
        - depguard
        - errcheck
        - errorlint
        - bodyclose
        - gosimple
        - ineffassign
        - misspell
        - nolintlint
        - nosprintfhostport
        - staticcheck
        - usetesting
        - typecheck
        - unconvert
        - unused
        - wastedassign
        - whitespace
        - gci

linters-settings:
  depguard:
    rules:
      # Name of a rule.
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use 'errors' or 'fmt' instead"
          - pkg: "golang.org/x/exp/slices"
            desc: "Use 'slices' instead"
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/openshift/cluster-monitoring-operator)
