apiVersion: v1
data:
  config.yaml: |-
    - "models":
      - "modelName": "A100"
        "pciID": "0x20b5"
      - "modelName": "RTX_A6000"
        "pciID": "0x2230"
      - "modelName": "RTX_4090"
        "pciID": "0x2717"
      - "modelName": "A40"
        "pciID": "0x2235"
      - "modelName": "V100"
        "pciID": "0x1df5"
      - "modelName": "A100 40G"
        "pciID": "0x20f1"
      - "modelName": "T400 4GB"
        "pciID": "0x1ff2"
      - "modelName": "Tesla T4"
        "pciID": "0x1eb8"
      "vendorID": "0x10de"
      "vendorName": "NVIDIA"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: node-exporter-accelerators-collector-config
  namespace: openshift-monitoring
