apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: ""
    metricRelabelings:
    - action: drop
      regex: (apiserver|go_sched|workqueue)_.+
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: false
      serverName: cluster-monitoring-operator.openshift-monitoring.svc
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-monitoring-operator
